name: JavaScript Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "main"
    paths:
      - "Source/JavaScript/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/JavaScript/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            .yarn/cache
            **/node_modules
            **/.eslintcache
            **/yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
  
      - name: Yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn

      - name: Build JS/TS
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn ci
